package presentacion.controlador;

public enum EventoNegocio {

	ACTUALIZAR_VISTA_PRINCIPAL,
	/** 
	 * <!-- begin-UML-doc -->
	 * <!-- end-UML-doc -->
	 * @generated "UML a Java (com.ibm.xtools.transform.uml2.java5.internal.UML2JavaTransform)"
	 */
	ACTUALIZAR_VISTA_ALTA_CELDAS, 
	//operaciones con celdas
	ACTUALIZAR_VISTA_CELDAS, ACTUALIZAR_VISTA_BAJA_CELDAS, ACTUALIZAR_VISTA_MODIFICAR_CELDAS, ACTUALIZAR_VISTA_DETALLES_CELDAS, ACTUALIZAR_VISTA_LISTAR_CELDAS, ALTA_CELDAS, BAJA_CELDAS, MODIFICAR_CELDAS, DETALLES_CELDAS, LISTAR_CELDAS, DETALLES_MODIFICAR_CELDAS,
	//operaciones con presos
	ACTUALIZAR_VISTA_PRESOS, ACTUALIZAR_VISTA_ALTA_PRESOS, ACTUALIZAR_VISTA_BAJA_PRESOS, ACTUALIZAR_VISTA_MODIFICAR_PRESOS, ACTUALIZAR_VISTA_DETALLES_PRESOS, ACTUALIZAR_VISTA_LISTAR_PRESOS, ACTUALIZAR_VISTA_ASIGNAR_CELDA, ACTUALIZAR_VISTA_MOSTRAR_CELDA, ALTA_PRESOS, BAJA_PRESOS, MODIFICAR_PRESOS, DETALLES_PRESOS, LISTAR_PRESOS, ASIGNAR_CELDA,DETALLES_MODIFICAR_PRESOS,PRESOS_POR_CELDA,ACTUALIZAR_VISTA_MOSTRAR_PRESOS_CELDA,
	//operaciones con pabellones
	ACTUALIZAR_VISTA_PABELLONES, ACTUALIZAR_VISTA_ALTA_PABELLONES, ACTUALIZAR_VISTA_BAJA_PABELLONES, ACTUALIZAR_VISTA_MODIFICAR_PABELLONES, ACTUALIZAR_VISTA_DETALLES_PABELLONES, ACTUALIZAR_VISTA_LISTAR_PABELLONES, ACTUALIZAR_VISTA_MOSTRAR_PABELLONES, ALTA_PABELLONES, BAJA_PABELLONES, MODIFICAR_PABELLONES, DETALLES_PABELLONES, LISTAR_PABELLONES, MOSTRAR_PABELLONES, DETALLES_MODIFICAR_PABELLONES
;

}
